### ISSUE TITLE
可以加个配置  全局class过滤名单吗？

### ISSUE THREAD

**Issue by zzengwei** [accforgit/AutoScssStruct4Vue#1]
全局样式以及提出来了，可以根据名单过滤掉class

**Comment by accforgit** [comment]
> 全局样式以及提出来了，可以根据名单过滤掉class

如果加这个配置的话，会引申出很多其他的逻辑，例如class过滤掉了，那么这个 class下面的子元素放到哪里？如果除了这个class还有其他class或id,要不要也过滤掉？后面还有一个和这一样的clas，但是后面这个 class我不想过滤掉，又怎么办？
所以这个配置可以加，但不好加，需要抉择的东西很多，性价比不高
如果不想要的话直接删掉即可，毕竟相比于写，删就容易多了

**Comment by 1340145680** [comment]
或许可以加一个选项让用户决定过滤后的子class是挂在父class还是抛弃掉。删除的话每个元素都有公共类，删除很麻烦

**Comment by 1340145680** [comment]
> > 全局样式以及提出来了，可以根据名单过滤掉class
> 
> 如果加这个配置的话，会引申出很多其他的逻辑，例如class过滤掉了，那么这个 class下面的子元素放到哪里？如果除了这个class还有其他class或id,要不要也过滤掉？后面还有一个和这一样的clas，但是后面这个 class我不想过滤掉，又怎么办？ 所以这个配置可以加，但不好加，需要抉择的东西很多，性价比不高 如果不想要的话直接删掉即可，毕竟相比于写，删就容易多了

或许可以加一个选项让用户决定过滤后的子class是挂在父class还是抛弃掉。删除的话每个元素都有公共类，删除很麻烦
